name: Labeler
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        if: github.repository == 'northwood-studios/SCPSL-Translations'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
